---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: _data/home/products.yml
  label: General
  match: "**/*"
- type: directory
  path: _shoes
  label: Shoes
  create: all
  match: "**/*"
- type: jekyll-pages
  label: Pages
  create: all
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: _authors
  label: Authors
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
